---
- file: dest=~/home-gitignore state=directory
- git: repo='https://github.com/funtaps/.dotfiles'
       dest=~/home-gitignore/dotfiles
       update=yes
       track_submodules=yes
       version=master
- file: src=~/home-gitignore/dotfiles/git/gitconfig
        dest=~/.gitconfig
        state=link
- file: src=~/home-gitignore/dotfiles/editors/nvim
        dest=~/.config/nvim
        state=link
- file: src=~/home-gitignore/dotfiles/shells/fishshell/fish
        dest=~/.config/fish
        state=link
- file: src=~/home-gitignore/dotfiles/shells/fishshell/fisherman
        dest=~/.config/fisherman
        state=link
- file: dest=~/.config/chromium state=directory
- file: src=~/.config/chromium
        dest=~/.config/google-chrome
        state=link
- file: dest=~/bin state=directory
- user: name=kfuntov shell=/usr/bin/fish
  become: true

# psysh
- name: Create composer directory
  file: dest=~/home-gitignore/composer state=directory
- name: Check psysh
  stat: path=~/home-gitignore/composer/vendor/psy/psysh/bin/psysh
  register: psysh_bin
- name: Install psysh
  composer: command=require arguments=psy/psysh working_dir=home-gitignore/composer
  when: not psysh_bin.stat.exists
- name: Link psysh to bin
  file: src=~/home-gitignore/composer/vendor/psy/psysh/bin/psysh
        dest=~/bin/psysh
        state=link

